ORG 00H

TOPLED EQU 10H	;Internal memory of RAM 
RLED EQU 13H
BOTTOMLED EQU 16H
LLED EQU 19H

DISPLAY0 EQU 11H
DISPLAY1 EQU 12H

        JMP MAIN
    
SSD:    DB 0C0H,0F9H,0A4H,0B0H,99H,92H,82H,0F8H,80H,90H    
     
        
MAIN:   MOV P2,#00H
        MOV P3,#00H
        CALL TOP_LIGHT
        MOV DPTR,#SSD
        CLR A

        MOV TOPLED,#10
        MOV RLED,#10
        MOV BOTTOMLED,#10
        MOV LLED,#20

        MOV R0,#20 ;gives a delay between DISPLAYS 
        
        MOV R7,#40
       
TOP_A:  MOV A,TOPLED
        CALL DIGIT  
       
SET1:     SETB P3.0  ;TURN LED0 OF SSD TOP ON
        CLR P3.1

        MOV A,DISPLAY0	;DISPLAY FIRST LOCATION 0 
        MOVC A,@A+DPTR
        MOV P2,A	;MOVE TO PORT2 TO DISPLAY 0

        CALL DELAY

        MOV P3,#00H	;CLEAR PORT3 

        SETB P3.1	;TURN LED1 OF SSD TOP 
        CLR P3.0
        MOV A,DISPLAY1	;DISPLAY SECOND LOCATION 1
        MOVC A,@A+DPTR	
        MOV P2,A	;MOVE TO PORT2 FOR DISPLAY 1
        CALL DELAY

        MOV P3,#00H	; CLEAR P3
        JMP SET3	;SHORT JUMP

SET2:     JMP TOP_A  ;TARGET OUT OF RANGE

SET3:   MOV A,RLED 	;A=10
        CALL DIGIT

        SETB P3.2	;LED 1 OF RIGHT SSD IS ON
        CLR P3.3
        MOV A,DISPLAY0	;MOVE 1 TO A
        MOVC A,@A+DPTR	;MOVE LOCATION 1 VALUE TO A
        MOV P2,A	;DISPLAY 1 
        CALL DELAY	
        MOV P3,#00H	;CLEAR PORT3
        SETB P3.3	;TURN LED 0 OF RIGHT SSD
        CLR P3.2
        MOV A,DISPLAY1	;MOVE 0 TO A
        MOVC A,@A+DPTR	;STORE LOCATION 0 AT A
        MOV P2,A	;DISPLAY 0
        CALL DELAY
        MOV P3,#00H	;CLEAR PORT3
        MOV A,BOTTOMLED	;MOVE 10 TO A
        CALL DIGIT	
	SETB P3.4	;LED1 OF BOTTOM SSD IS ON
        CLR P3.5	
        MOV A,DISPLAY0	;A=1
        MOVC A,@A+DPTR	;STORE LOCATION 1 AT A
        MOV P2,A	;DISPLAY 1
        CALL DELAY	
        MOV P3,#00H	;CLEAR PORT3
        SETB P3.5	;LED0 OF BOTTOM SSD IF ON
        CLR P3.4	;
        MOV A,DISPLAY1	;A=0
        MOVC A,@A+DPTR	;STORE LOCATION 0 VALUE AT A
        MOV P2,A	;DISPLAY 0	
        CALL DELAY
        MOV P3,#00H	;CLEAR PORT3     
        MOV A,LLED	;A=20
        CALL DIGIT
        SETB P3.6	;LED1 OF LEFT SSD IS ON
        CLR P3.7
        MOV A,DISPLAY0	;A=2
        MOVC A,@A+DPTR	;MOVE AT LOCATION 2
        MOV P2,A	;DISPLAY 2
        CALL DELAY	
        MOV P3,#00H	;CLEAR PORT3
        SETB P3.7	;LED0 OF LEFT SSD IS ON
        CLR P3.6
        MOV A,DISPLAY1	;A=0
        MOVC A,@A+DPTR	;MOVE AT LOCATION 0
        MOV P2,A	;DISPLAY 0
        CALL DELAY
        MOV P3,#00H	;CLEAR PORT3


        DJNZ R0,SET2
        MOV R0,#20

	
CHECK1:	
	CJNE R2,#1, CHECK11
	MOV TOPLED, #10


	CHECK11:
DJNZ TOPLED,CHECK2 ;IF TOPLED=0, MOVE TO LEFTLED
	

        
	MOV TOPLED,#20	;MOVE 20 TO TOP SSD WHEN COUNT HAS FINISHED
	MOV RLED,#11
	MOV BOTTOMLED, #11
	MOV LLED, #11
	MOV R2,#0
	CALL RIGHT_LIGHT


CHECK2:   
	DJNZ RLED,CHECK3;MOVE 20 TO RIGHT SSD WHEN COUNT HAS FINISHED
      	MOV TOPLED,#10	;MOVE 20 TO TOP SSD WHEN COUNT HAS FINISHED
	MOV RLED,#20
	MOV BOTTOMLED,#11
	MOV LLED,#11
	MOV R2, #1
	CALL BOTTOM_LIGHT

	


CHECK3: DJNZ BOTTOMLED,CHECK4	;MOVE 10 TO BOTTOM SSD WHEN COUNT HAS FINISHED

        MOV TOPLED,#10	;MOVE 20 TO TOP SSD WHEN COUNT HAS FINISHED
	MOV RLED,#10
	MOV BOTTOMLED, #20
	MOV LLED, #11
	MOV R2, #0
	CALL LEFT_LIGHT

CHECK4: DJNZ LLED,X4 	;MOVE 20 TO RIGHT SSD WHEN COUNT HAS FINISHED   

X4:     DJNZ R7,L1
        JMP MAIN

L1:     JMP TOP_A     
										
										DELAY:  MOV R4,#5
										H2:     MOV R5,#0FFH
										H1:     DJNZ R5,H1
										        DJNZ R4,H2
										        RET

TOP_LIGHT:  MOV P1,#54H
        MOV P0,#02H
        RET


RIGHT_LIGHT:  MOV P1,#0A1H ;TURN GREEN LIGHT
        MOV P0,#02H
        RET

BOTTOM_LIGHT:  MOV P1,#09H
       MOV P0,#05H
       RET

LEFT_LIGHT:  MOV P1,#4AH
       MOV P0,#08H
       RET


DIGIT:
	MOV B,#10
        DIV AB
	MOV DISPLAY0,A
	MOV DISPLAY1,B
	RET
END
